language: php

php:
  - 7.1.16

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - createdb forge

script:
  - vendor/bin/phpunit

services:
  - pgsql
